language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - python setup.py install

script:
  - python setup.py test

after_success:
  - coverage run --source pygeometa setup.py test
  - coverage report -m
